docs_dir: doc
site_name: GEMS - Generic Energy system Modelling Scheme
repo_url: https://github.com/AntaresSimulatorTeam/GEMS
edit_uri: edit/doc/doc/

theme:
  name: material
  logo: assets/gemsV2.png
  favicon: assets/gemsV2.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - Home: index.md
    - Context of GEMS: 0_Home/1_context_GEMS.md
    - Release Notes: 0_Home/2_release_notes.md
  - Overview:
      - Concepts:
          - Core Concepts: 1_Overview/Concepts/1_core_concepts.md
          - Architecture: 1_Overview/Concepts/2_architecture.md
          - Features: 1_Overview/Concepts/3_features_usecase.md
      - GEMS Interpreters:
          - Antares Simulator: 1_Overview/GEMS_Interpreters/2_antares_simulator_modeler.md
          - GemsPy: 1_Overview/GEMS_Interpreters/1_gemspy.md
                
      - References:
            - Classification of models: 1_Overview/References/1_Classification_Configuration.md
            - Libraries of models: 1_Overview/References/2_Libraries.md
            - Users of GEMS: 1_Overview/References/3_Users.md
  - Getting Started:
      - Installation:
        - Antares Simulator's GEMS Interpreter: 2_Getting_Started/1A_modeler_installation.md
        - GEMSPy: 2_Getting_Started/1B_gemspy_installation.md
      - Support: 2_Getting_Started/1C_support.md
  - User Guide:
      - Introduction: 3_User_Guide/1_introduction.md
      - Mathematical Syntax: 3_User_Guide/2_mathematical_syntax.md
      - File Structure:
        - Overview: 3_User_Guide/3_GEMS_File_Structure/1_overview.md
        - Library File: 3_User_Guide/3_GEMS_File_Structure/2_library.md
        - System File: 3_User_Guide/3_GEMS_File_Structure/3_system.md
        - Data Series File: 3_User_Guide/3_GEMS_File_Structure/4_data_series.md
        - Scenario Builder File: 3_User_Guide/3_GEMS_File_Structure/5_scenario_builder.md
        - Solver and Optimisation Configuration: 3_User_Guide/3_GEMS_File_Structure/6_solver_optimization.md
        - Taxonomy File: 3_User_Guide/3_GEMS_File_Structure/7_taxonomy.md
        - Business Views Configuration: 3_User_Guide/3_GEMS_File_Structure/8_business_view.md
      - Theoretical Concepts:
        - Hypergraph Structure: 3_User_Guide/4_Theoretical_Concepts/1_hypergraph_structure.md
        - Optimisation Problem: 3_User_Guide/4_Theoretical_Concepts/2_optimization_problem.md
      - Outputs:
        - Simulation Table: 3_User_Guide/5_Outputs/1_simulation_table.md
        - Optimisation Problem Files: 3_User_Guide/5_Outputs/2_optimization_problem_files.md
        - Business View: 3_User_Guide/5_Outputs/3_business_view.md
  - Interoperability:
      - PyPSA: 4_Interoperability/1_pypsa.md
      - Antares Legacy Format: 4_Interoperability/2_antares_legacy.md
      - Antares Hybrid Mode: 4_Interoperability/3_hybrid.md
  - Examples:
      - Tutorial - Simple economic dispatch problem: 5_Examples/1_optimization_problem.md
      - Antares Simulator Hybrid study: 5_Examples/2_hybrid.md
  - Support & Contributing:
      - FAQ: 6_Support_Contributing/1_faq.md
      - Contact: 6_Support_Contributing/2_contact.md
      - Contributing: 6_Support_Contributing/3_contributing.md
