docs_dir: doc
site_name: GEMS - Generic Energy system Modelling Scheme
repo_url: https://github.com/AntaresSimulatorTeam/GEMS
edit_uri: edit/doc/doc/

theme:
  name: material
  logo: assets/gemsV2.png
  favicon: assets/gemsV2.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - Home: index.md
    - Context of GEMS: 0_Home/1_context_GEMS.md
    - Release Notes: 0_Home/2_release_notes.md 
  - Overview:
      - Concepts:
          - Core Concepts: 1_Overview/Concepts/1_core_concepts.md
          - Architecture: 1_Overview/Concepts/2_architecture.md
          - Features: 1_Overview/Concepts/3_features_usecase.md
      - GEMS Interpreters:
          - Antares Simulator: 1_Overview/GEMS_Interpreters/2_antares_simulator_modeler.md
          - GemsPy: 1_Overview/GEMS_Interpreters/1_gemspy.md
      - References:
            - Classification of models: 1_Overview/References/1_Classification_Configuration.md
            - Libraries of models: 1_Overview/References/2_Libraries.md
            - Users of GEMS: 1_Overview/References/3_Users.md
  - Getting Started:
      - Installation:
        - Antares Simulator's GEMS Interpreter: 2_Getting_Started/1A_modeler_installation.md
        - GEMSPy: 2_Getting_Started/1B_gemspy_installation.md
      - Quick Start Examples:
        - Adequacy: 2_Getting_Started/2A_adequacy.md
        - Unit Commitment: 2_Getting_Started/2B_QSE_unit_commitment.md
      - Support: 2_Getting_Started/1C_support.md
  - User Guide:
      - Syntax: 3_User_Guide/1_syntax.md
      - Inputs: 3_User_Guide/2_inputs.md
      - Antares Hybrid Mode Inputs: 3_User_Guide/3_hybrid_inputs.md
      - Outputs: 3_User_Guide/4_outputs.md
      - Optimization: 3_User_Guide/5_optimization.md
      - Glossary: 3_User_Guide/6_glossary.md
  - Interoperability:
      - PyPSA: 4_Interoperability/1_pypsa.md
      - Antares Legacy Format: 4_Interoperability/2_antares_legacy.md
      - Antares Hybrid Mode: 4_Interoperability/3_hybrid.md
  - Examples:
      - Tutorial - Simple economic dispatch problem: 5_Examples/1_optimization_problem.md
      - Antares Simulator Hybrid study: 5_Examples/2_hybrid.md
  - Support & Contributing:
      - FAQ: 6_Support_Contributing/1_faq.md
      - Contact: 6_Support_Contributing/2_contact.md
      - Contributing: 6_Support_Contributing/3_contributing.md
